--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/angga7togk/CodeRedeem
build-by-default: true
branches:
- main
projects:
  CodeRedeem:
    path: ""
    libs:
      - src: Infernus101/FormAPI/libFormAPI
        version: ^2.1.0
  icon:
    path: "icon2.png"
...
