name: CodeRedeem
main: angga7togk\coderedeem\CodeRedeem
version: 1.2.0
api: 4.0.0
author: Angga7Togk
description: "CodeRedeem"

commands:
  coderedeem:
    description: "Open The CodeRedeem Menu"
    permission: coderedeem.cmd
    aliases: [cr]
  setcode:
    description: "Set CodeRedeem"
    permission: coderedeem.admin

permissions:
  coderedeem.cmd:
    default: true
  coderedeem.admin:
    default: op