name: CodeRedeem
main: Angga7Togk\CodeRedeem\Main
version: 1.0.0
api: 4.0.0
author: Angga7Togk
description: "CodeRedeem Plugin"

commands:
  coderedeem:
    description: "Open The CodeRedeem Menu"
    permission: coderedeem.cmd
  codereset:
    description: "Reset Data Player."
    permission: codereset.cmd

permissions:
  coderedeem.cmd:
    default: true
  codereset.cmd:
    default: op