Title: "CodeRedeem"
Content: "enter the correct redeem code, and get a prize."

Prize:
  Message-Succes: "Congratulations, {player} have won the code redeem prize."
  Message-Failed: "Your code is wrong, please try again."
  Message-Claimed: "You have got a Code Redem prize."

Config-Version: "1.0"